version: "3.8"
services:
  postgres:
    image: ankane/pgvector
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resumematch
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"